import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import Layout from '../components/layout/layout'
import Blog from '../components/blog/Blog'

export default function Home({posts}) {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout title='Главная'>
        <h1>Интересный блок</h1>
        <div className='posts'></div>
        {posts.map(post => <Blog key={post.id} title={post.title} description={post.body} id={post.id}/>)}
      </Layout>
    </div>
  )
}

export const getServerSideProps = async() => {

  const data = await fetch(`https://jsonplaceholder.typicode.com/posts`)
  const posts = await data.json()

  return  {
    props: {posts},
  }
}