import Head from 'next/head'
import Link from 'next/link'

export default function Item() {
    return(
        <div>
        <Head>
        <title>Item pages</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

        <h1>Item pages</h1>
        <Link href='/'>
          <a>
            Home pages
          </a>
        </Link>
        </div>
    )
}